### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by StijnVrolijk**
Improves and completes the documentation for the bunddle

### CODE REVIEW

**Comment by bjorvack** [comment]
Als je toch een menu maakt kan je die dan niet beter door trekken, nu ben je die plots kwijt na een aantal stappen

**Comment by StijnVrolijk** [comment]
@bjorvack I don't really know what you're talking about? I'm treating the users section as a subsection because it's the most important. The steps before and after are just steps you have to go through once, the users section is mostly used for reference it think. I will add an overview to the first page though.

**Comment by bjorvack** [comment]
@StijnVrolijk That would be great :)

**Comment by ohvitorino** [comment]
@StijnVrolijk I would also add the `use` statements when defining the user classes for example.

**Comment by StijnVrolijk** [comment]
@ohvitorino anywhere a class was used that wasn't referenced before I explained in the leading text where to find these classes.

@sumocoders/php-team what do you think about adding use statements to the code snippets themselves?

**Comment by tijsverkoyen** [comment]
I would add the `use`-statements

**Comment by ohvitorino** [comment]
An `encoders` snippet is also missing.

```
# app/config/security.yml
security:
    encoders:
        SumoCoders\FrameworkMultiUserBundle\Entity\User: sha512
```

**Pull request merged**
